import React from 'react';

// Case studies generated by Scott (tgm-checkmate daily flywheel, 2026-05-30)
const CASE_STUDIES = [
  {
    id: 'dev-team-180k',
    avatar: 'KL',
    avatarBg: '#003A8C',
    title: 'How a 3-Person Development Team Won $180k in 90 Days',
    role: 'Development Director',
    org: 'Mid-size Education Nonprofit',
    metric: '$180k',
    metricLabel: 'in 90 days',
    before: {
      label: 'Before TGM',
      points: [
        '12 hrs per proposal',
        '22% win rate',
        'Funder research scattered across spreadsheets',
        'Team burning out on deadline crunches',
      ],
    },
    after: {
      label: 'After TGM',
      points: [
        '3.5 hrs per proposal',
        '41% win rate',
        'Funder alignment scored in 45 min',
        'Director freed up for funder relationships',
      ],
    },
    mechanism:
      "TGM's funder alignment engine cut research from 4 hours to 45 minutes per grant. Proposal builder templates eliminated blank-page paralysis. Deadline tracking consolidated 6 spreadsheets into one dashboard.",
  },
  {
    id: 'agency-cost-cut',
    avatar: 'RB',
    avatarBg: '#7E22CE',
    title: 'How an Agency Cut AI Tool Costs by 40% Without Losing Capability',
    role: 'Operations Lead',
    org: '10-Person Digital Agency',
    metric: '$12k',
    metricLabel: 'saved annually',
    before: {
      label: 'Before TGM',
      points: [
        '8 overlapping AI tools',
        '$2,400/mo in subscriptions',
        'Team unsure which tool to use',
        'Duplicate work across platforms',
      ],
    },
    after: {
      label: 'After TGM',
      points: [
        'Consolidated to 5 tools',
        '$1,400/mo — 40% reduction',
        'Clear per-task workflows',
        '15% productivity increase',
      ],
    },
    mechanism:
      "TGM's workflow identified 3 tools with direct feature overlap. Stack consolidation covered all use cases at lower cost. Full transition completed in 2 weeks.",
  },
];

const STAT_BAR = [
  { value: '3.5 hrs', label: 'Avg proposal time' },
  { value: '41%',    label: 'Win rate (up from 22%)' },
  { value: '$180k',  label: 'Grants won in 90 days' },
  { value: '40%',    label: 'Cost reduction' },
];

/**
 * CaseStudiesSection
 *
 * Props:
 *   variant  "full" (default) — stat bar + two cards
 *            "compact"        — two cards only, no stat bar
 *            "inline"         — single horizontal card strip for tight spaces (signup)
 */
export default function CaseStudiesSection({ variant = 'full' }) {
  return (
    <section
      aria-label="Customer results"
      style={{
        background: variant === 'inline' ? 'rgba(0,58,140,.04)' : '#F8F9FC',
        padding: variant === 'inline' ? '32px 24px' : '72px 24px',
        borderTop: variant === 'inline' ? '1px solid rgba(0,58,140,.1)' : 'none',
      }}
    >
      <div style={{ maxWidth: variant === 'inline' ? 880 : 1100, margin: '0 auto' }}>

        {/* Label + heading */}
        <div style={{ textAlign: 'center', marginBottom: variant === 'inline' ? 24 : 8 }}>
          <span style={{
            display: 'inline-block',
            background: 'rgba(212,175,55,.15)',
            color: '#B8960C',
            fontSize: 11, fontWeight: 700,
            padding: '4px 14px', borderRadius: 20,
            letterSpacing: '0.08em', textTransform: 'uppercase',
          }}>
            Real Results
          </span>
        </div>

        {variant !== 'inline' && (
          <>
            <h2 style={{
              textAlign: 'center', fontSize: 32, fontWeight: 800,
              color: 'var(--tgm-navy, #0A0F1A)', margin: '8px 0 10px',
            }}>
              Grant writers win more with TGM
            </h2>
            <p style={{
              textAlign: 'center', color: 'var(--tgm-muted, #6B7280)',
              marginBottom: 48, maxWidth: 520, marginLeft: 'auto', marginRight: 'auto',
            }}>
              Not projections. Not demos. Outcomes from real teams using TGM in production.
            </p>
          </>
        )}

        {/* Stat bar — full variant only */}
        {variant === 'full' && (
          <div style={{
            display: 'flex', flexWrap: 'wrap', justifyContent: 'center',
            gap: 0, marginBottom: 56,
            background: 'linear-gradient(135deg, #0A0F1A 0%, #003A8C 100%)',
            borderRadius: 16, overflow: 'hidden',
          }}>
            {STAT_BAR.map(({ value, label }, i) => (
              <div key={label} style={{
                flex: '1 1 160px', padding: '28px 24px', textAlign: 'center',
                borderRight: i < STAT_BAR.length - 1 ? '1px solid rgba(255,255,255,.1)' : 'none',
              }}>
                <p style={{ margin: 0, fontSize: 32, fontWeight: 800, color: '#D4AF37', lineHeight: 1 }}>
                  {value}
                </p>
                <p style={{ margin: '6px 0 0', fontSize: 12, color: 'rgba(255,255,255,.65)', fontWeight: 500 }}>
                  {label}
                </p>
              </div>
            ))}
          </div>
        )}

        {/* Case study cards */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: variant === 'inline' ? '1fr' : 'repeat(auto-fit, minmax(460px, 1fr))',
          gap: 24,
        }}>
          {CASE_STUDIES.map((cs) => (
            <CaseStudyCard key={cs.id} cs={cs} compact={variant === 'inline'} />
          ))}
        </div>

      </div>
    </section>
  );
}

function CaseStudyCard({ cs, compact }) {
  return (
    <div style={{
      background: '#fff',
      borderRadius: 16,
      border: '1px solid #EAECF0',
      boxShadow: '0 2px 12px rgba(0,0,0,.06)',
      overflow: 'hidden',
    }}>
      {/* Card header */}
      <div style={{
        background: 'linear-gradient(135deg, #0A0F1A 0%, #003A8C 100%)',
        padding: compact ? '20px 24px' : '24px 28px',
        display: 'flex', alignItems: 'flex-start', gap: 16,
      }}>
        <div style={{
          width: 44, height: 44, borderRadius: '50%', flexShrink: 0,
          background: cs.avatarBg, border: '2px solid rgba(212,175,55,.5)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontSize: 13, fontWeight: 700, color: '#fff',
        }}>
          {cs.avatar}
        </div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <p style={{ margin: 0, fontSize: compact ? 14 : 15, fontWeight: 700, color: '#fff', lineHeight: 1.3 }}>
            {cs.title}
          </p>
          <p style={{ margin: '4px 0 0', fontSize: 12, color: 'rgba(255,255,255,.6)' }}>
            {cs.role} · {cs.org}
          </p>
        </div>
        <div style={{ textAlign: 'right', flexShrink: 0 }}>
          <p style={{ margin: 0, fontSize: 26, fontWeight: 800, color: '#D4AF37', lineHeight: 1 }}>
            {cs.metric}
          </p>
          <p style={{ margin: '2px 0 0', fontSize: 11, color: 'rgba(255,255,255,.55)', whiteSpace: 'nowrap' }}>
            {cs.metricLabel}
          </p>
        </div>
      </div>

      {/* Before / After */}
      <div style={{
        display: 'grid', gridTemplateColumns: '1fr 1fr',
        borderBottom: '1px solid #F0F0F0',
      }}>
        <BeforeAfterCol
          label={cs.before.label}
          points={cs.before.points}
          type="before"
          compact={compact}
        />
        <BeforeAfterCol
          label={cs.after.label}
          points={cs.after.points}
          type="after"
          compact={compact}
        />
      </div>

      {/* Mechanism */}
      {!compact && (
        <div style={{ padding: '16px 28px 20px' }}>
          <p style={{ margin: 0, fontSize: 12, fontWeight: 700, color: '#003A8C', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 6 }}>
            How it happened
          </p>
          <p style={{ margin: 0, fontSize: 13, color: '#374151', lineHeight: 1.6 }}>
            {cs.mechanism}
          </p>
        </div>
      )}
    </div>
  );
}

function BeforeAfterCol({ label, points, type, compact }) {
  const isBefore = type === 'before';
  return (
    <div style={{
      padding: compact ? '14px 16px' : '18px 20px',
      borderRight: isBefore ? '1px solid #F0F0F0' : 'none',
      background: isBefore ? '#FAFAFA' : '#F0FDF4',
    }}>
      <p style={{
        margin: '0 0 10px', fontSize: 11, fontWeight: 700,
        textTransform: 'uppercase', letterSpacing: '0.07em',
        color: isBefore ? '#9CA3AF' : '#16A34A',
      }}>
        {label}
      </p>
      <ul style={{ margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 7 }}>
        {points.map((pt) => (
          <li key={pt} style={{ display: 'flex', alignItems: 'flex-start', gap: 7, fontSize: 13, color: '#374151', lineHeight: 1.4 }}>
            <span style={{
              flexShrink: 0, marginTop: 1,
              color: isBefore ? '#EF4444' : '#16A34A',
              fontWeight: 700, fontSize: 14,
            }}>
              {isBefore ? '✕' : '✓'}
            </span>
            {pt}
          </li>
        ))}
      </ul>
    </div>
  );
}
