import React from 'react';
import { Link } from 'react-router-dom';

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 760, margin: '0 auto', padding: '60px 24px', fontFamily: 'inherit', color: '#1e293b' }}>
      <Link to="/" style={{ color: '#003A8C', fontSize: 14, textDecoration: 'none', fontWeight: 600 }}>← Back to GrantsMaster</Link>
      <h1 style={{ fontSize: 32, fontWeight: 800, color: '#0A0F1A', margin: '32px 0 8px' }}>Terms of Service</h1>
      <p style={{ color: '#64748b', fontSize: 14, marginBottom: 40 }}>Last updated: May 2, 2026</p>

      {[
        {
          title: '1. Acceptance of Terms',
          body: `By creating an account or using GrantsMaster ("the Service"), you agree to these Terms of Service. If you do not agree, do not use the Service.`,
        },
        {
          title: '2. Description of Service',
          body: `GrantsMaster is an AI-powered grant writing platform that helps nonprofit organizations and grant writers create, edit, and manage grant proposals. The Service includes AI-assisted drafting, workspace management, and collaboration tools.`,
        },
        {
          title: '3. Account Responsibilities',
          body: `You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. You must provide accurate information when creating your account. You may not share your account with others or use the Service for any unlawful purpose.`,
        },
        {
          title: '4. Subscription & Billing',
          body: `Paid plans are billed through LemonSqueezy. Lifetime plans are a one-time purchase with no recurring charges. Subscription plans renew automatically unless cancelled. Refunds are handled on a case-by-case basis — contact support@thegrantsmaster.com within 7 days of purchase.`,
        },
        {
          title: '5. AI-Generated Content',
          body: `Content generated by the AI assistant is provided as a starting point and should be reviewed and edited before submission. GrantsMaster does not guarantee that AI-generated content will meet any specific funder's requirements. You are solely responsible for the accuracy and appropriateness of submitted grant proposals.`,
        },
        {
          title: '6. Intellectual Property',
          body: `You retain full ownership of all content you create using the Service, including drafts and proposals. GrantsMaster retains ownership of the platform, software, and AI models. You grant GrantsMaster a limited license to process your content solely to provide the Service.`,
        },
        {
          title: '7. Limitation of Liability',
          body: `GrantsMaster is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service, including loss of grant funding or missed deadlines.`,
        },
        {
          title: '8. Termination',
          body: `We reserve the right to suspend or terminate accounts that violate these Terms. You may cancel your account at any time from the billing portal.`,
        },
        {
          title: '9. Changes to Terms',
          body: `We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the new Terms.`,
        },
        {
          title: '10. Contact',
          body: `For questions about these Terms, contact us at: support@thegrantsmaster.com`,
        },
      ].map(({ title, body }) => (
        <div key={title} style={{ marginBottom: 32 }}>
          <h2 style={{ fontSize: 18, fontWeight: 700, color: '#003A8C', marginBottom: 8 }}>{title}</h2>
          <p style={{ fontSize: 15, lineHeight: 1.7, color: '#334155' }}>{body}</p>
        </div>
      ))}
    </div>
  );
}
